version: "3.5"

services:
  app:
    build:
      target: development
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "9229:9229" # Chrome DevTools Debugger

  nginx:
    image: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./docker/nginx.conf:/tmp/fxdev.conf
    environment:
      - DOMAIN=_
      - PORTA_FRONT=8000
      - PORTA_BACK=8001
    depends_on:
      - app
    command: /bin/bash -c "envsubst < /tmp/fxdev.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
